### ISSUE TITLE
Immigration should fail more gracefully on user error

### ISSUE THREAD

**Issue by marick** [marick/suchwow#1]
There might be a better way of saying "you tried to immigrate a nonexistent var" than:

```
Exception in thread "main" java.lang.NullPointerException, compiling:(appointments/types.clj:6:1)
    at clojure.lang.Compiler.load(Compiler.java:7239)
    at clojure.lang.RT.loadResourceScript(RT.java:371)
    at clojure.lang.RT.loadResourceScript(RT.java:362)
    at clojure.lang.RT.load(RT.java:446)
```

**Comment by marick** [comment]
Fixed in 5.2.1
